### ISSUE TITLE
Support for .NET 4.5

### ISSUE THREAD

**Issue by Fredz66** [hanssens/localstorage#20]
Would it be possible to support .NET 4.5 or is there an incompatibility that requires .NET 4.6 ?

**Comment by hanssens** [comment]
In theory it could be done. The only external dependency is Newtonsoft.Json, which also has support for the older frameworks.

However, in terms of "supporting it" I'm a bit reluctant to do so. Reason is that [Microsoft itself phased out support for .NET 4.5.1](https://github.com/Microsoft/dotnet/blob/master/releases/README.md) (and lower). I'm planning to upgrade the library to netstandard2, at which time I'd like to investigate if there are any blocking reasons that prevent targeting .NET 4.5 as well. It will be on an "as is" level if there are no showstoppers.

**Comment by hanssens** [comment]
You triggered me, so at an off moment I'm currently working on the upgrade to netstandard 2.0 and to put it simply: [Microsoft Docs recommends](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/) only targeting .NET 4.6.1 or higher. Also the docs on the [.NET Implementation Support](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) mention the same. 

So sorry, @Fredz66 but I will not support for .NET 4.5 due to this. However, there is nothing stopping you from creating a fork if you really require it.

**Comment by Fredz66** [comment]
Ok, thanks for the effort anyway.
